### PR TITLE
French update

### PR DESCRIPTION
**Pull request by fxbenard**

### CODE REVIEW

**Comment by fxbenard** [comment]
First addon fully translated and reviewed in French.

**Comment by RealRaven2000** [comment]
Nice one! did you see the recent changes to the 2 items "whats-new-list" and "newsSection"? I only modified these very recently...

**Comment by RealRaven2000** [comment]
these are the items. I am going to check anyway when I merge...
```json
  "newsSection": {
    "message": "{P1} This latest edition of $addonName$ finally restores the beloved custom icon feature to work with the completely recreated folder tree of Thunderbird 115. {P2}{P1} With this you can add custom icons to any folder. Right-click any folder to add a custom icon from a file. See the feature comparison below on any license restrictions. {P2}",
    "placeholders": {
      "addonName": {
        "content": "$1",
        "example": "QuickFolders"
      }
    }
  },

  "whats-new-list": {
    "message": "{L1} Added custom icons in folder tree in Thunderbird 115. [issue 399] {L2} {L1} Made registration screen less tall.{L2} {L1} QuickFolders now supports svg icons in tabs. [issue 407] {L2} {L1} Fixed: Open folder from QF Tab while viewing a message.{L2}{L1} The Navigation Bar now avoids horizontal overflow in columns view. {L2}{L1} Fixed: the 'Empty Junk' commands were intermittently hidden from context menus in folder tree [issue 406]{L2}{L1} Dragging mail to Current Folder tab did not open subfolders popup.{L2}{L1}'Create new subfolder' menuitem was missing when dragging mail to a QuickFolders Tab. [issue 420]{L2}"
  },

```

**Comment by RealRaven2000** [comment]
Can you remove [QuickFolders-Config.json](https://github.com/RealRaven2000/QuickFolders/compare/ESR115...fxbenard:QuickFolders:ESR115#diff-dbfad4ba81ea34cd7d77587ec4a6db4ed506c4f37c38de0724ced9c17c34919e) from your branch? This is not part of the QuickFolders build... It's an export / temporary file which you should not save within the source code files.

**Comment by fxbenard** [comment]
Done

**Pull request merged**
